"""Public contracts for object-style template expressions."""

from __future__ import annotations

from dataclasses import dataclass

from pykara.declaration import Scope


@dataclass(frozen=True, slots=True)
class ExpressionObjectSpecification:
    """Describe one root object exposed to inline expressions."""

    name: str
    available_scopes: frozenset[Scope]
    description: str


@dataclass(frozen=True, slots=True)
class ExpressionPropertySpecification:
    """Describe one public property exposed by an expression object."""

    object_name: str
    name: str
    type: str
    available_scopes: frozenset[Scope]
    source_variable: str | None
    description: str


LINE_SCOPES = frozenset({Scope.LINE, Scope.WORD, Scope.SYL, Scope.CHAR})
WORD_SCOPES = frozenset({Scope.WORD, Scope.SYL, Scope.CHAR})
ALL_SCOPES = frozenset(
    {Scope.SETUP, Scope.LINE, Scope.WORD, Scope.SYL, Scope.CHAR}
)


EXPRESSION_OBJECT_SPECIFICATIONS: dict[str, ExpressionObjectSpecification] = {
    "line": ExpressionObjectSpecification(
        name="line",
        available_scopes=LINE_SCOPES,
        description="Current generated line available to inline expressions.",
    ),
    "word": ExpressionObjectSpecification(
        name="word",
        available_scopes=WORD_SCOPES,
        description="Current word available to inline expressions.",
    ),
    "syl": ExpressionObjectSpecification(
        name="syl",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        description="Current syllable available to inline expressions.",
    ),
    "char": ExpressionObjectSpecification(
        name="char",
        available_scopes=frozenset({Scope.CHAR}),
        description="Current character available to inline expressions.",
    ),
    "style": ExpressionObjectSpecification(
        name="style",
        available_scopes=LINE_SCOPES,
        description="Style of the current generated line.",
    ),
    "metadata": ExpressionObjectSpecification(
        name="metadata",
        available_scopes=LINE_SCOPES,
        description="Script-level metadata available to inline expressions.",
    ),
    "assets": ExpressionObjectSpecification(
        name="assets",
        available_scopes=ALL_SCOPES,
        description="Collection of ready-to-use named resources.",
    ),
}

EXPRESSION_PROPERTY_SPECIFICATIONS: dict[
    tuple[str, str], ExpressionPropertySpecification
] = {
    ("line", "layer"): ExpressionPropertySpecification(
        object_name="line",
        name="layer",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="layer",
        description="Current generated line layer.",
    ),
    ("line", "actor"): ExpressionPropertySpecification(
        object_name="line",
        name="actor",
        type="str",
        available_scopes=LINE_SCOPES,
        source_variable="actor",
        description="Current generated line actor.",
    ),
    ("line", "raw_text"): ExpressionPropertySpecification(
        object_name="line",
        name="raw_text",
        type="str",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Original source line text with ASS tags intact.",
    ),
    ("line", "text"): ExpressionPropertySpecification(
        object_name="line",
        name="text",
        type="str",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Visible line text without ASS tags.",
    ),
    ("line", "trimmed_text"): ExpressionPropertySpecification(
        object_name="line",
        name="trimmed_text",
        type="str",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Visible line text without ASS tags or outer spaces.",
    ),
    ("line", "start"): ExpressionPropertySpecification(
        object_name="line",
        name="start",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_start",
        description="Line start time in ms.",
    ),
    ("line", "end"): ExpressionPropertySpecification(
        object_name="line",
        name="end",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_end",
        description="Line end time in ms.",
    ),
    ("line", "dur"): ExpressionPropertySpecification(
        object_name="line",
        name="dur",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_dur",
        description="Total line duration in ms.",
    ),
    ("line", "mid"): ExpressionPropertySpecification(
        object_name="line",
        name="mid",
        type="float",
        available_scopes=LINE_SCOPES,
        source_variable="line_mid",
        description="Line temporal midpoint.",
    ),
    ("line", "i"): ExpressionPropertySpecification(
        object_name="line",
        name="i",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_i",
        description="Line index in the document.",
    ),
    ("line", "left"): ExpressionPropertySpecification(
        object_name="line",
        name="left",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_left",
        description="Line left X position.",
    ),
    ("line", "center"): ExpressionPropertySpecification(
        object_name="line",
        name="center",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_center",
        description="Line horizontal center.",
    ),
    ("line", "right"): ExpressionPropertySpecification(
        object_name="line",
        name="right",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_right",
        description="Line right X position.",
    ),
    ("line", "width"): ExpressionPropertySpecification(
        object_name="line",
        name="width",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_width",
        description="Line width in pixels.",
    ),
    ("line", "top"): ExpressionPropertySpecification(
        object_name="line",
        name="top",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_top",
        description="Line top Y position.",
    ),
    ("line", "middle"): ExpressionPropertySpecification(
        object_name="line",
        name="middle",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_middle",
        description="Line vertical center.",
    ),
    ("line", "bottom"): ExpressionPropertySpecification(
        object_name="line",
        name="bottom",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_bottom",
        description="Line bottom Y position.",
    ),
    ("line", "height"): ExpressionPropertySpecification(
        object_name="line",
        name="height",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_height",
        description="Line height in pixels.",
    ),
    ("line", "x"): ExpressionPropertySpecification(
        object_name="line",
        name="x",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_x",
        description="Line anchor X position.",
    ),
    ("line", "y"): ExpressionPropertySpecification(
        object_name="line",
        name="y",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable="line_y",
        description="Line anchor Y position.",
    ),
    ("line", "syls"): ExpressionPropertySpecification(
        object_name="line",
        name="syls",
        type="tuple[object, ...]",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description=(
            "Read-only karaoke syllables with timing and geometry fields "
            "such as start_time, end_time, duration, and center."
        ),
    ),
    ("word", "start"): ExpressionPropertySpecification(
        object_name="word",
        name="start",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_start",
        description="Word start time in ms.",
    ),
    ("word", "end"): ExpressionPropertySpecification(
        object_name="word",
        name="end",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_end",
        description="Word end time in ms.",
    ),
    ("word", "dur"): ExpressionPropertySpecification(
        object_name="word",
        name="dur",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_dur",
        description="Word duration in ms.",
    ),
    ("word", "kdur"): ExpressionPropertySpecification(
        object_name="word",
        name="kdur",
        type="float",
        available_scopes=WORD_SCOPES,
        source_variable="word_kdur",
        description="Word duration in centiseconds.",
    ),
    ("word", "mid"): ExpressionPropertySpecification(
        object_name="word",
        name="mid",
        type="float",
        available_scopes=WORD_SCOPES,
        source_variable="word_mid",
        description="Word temporal midpoint.",
    ),
    ("word", "n"): ExpressionPropertySpecification(
        object_name="word",
        name="n",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_n",
        description="Total number of words in the line.",
    ),
    ("word", "i"): ExpressionPropertySpecification(
        object_name="word",
        name="i",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_i",
        description="Word index in the line.",
    ),
    ("word", "left"): ExpressionPropertySpecification(
        object_name="word",
        name="left",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_left",
        description="Word left X position.",
    ),
    ("word", "center"): ExpressionPropertySpecification(
        object_name="word",
        name="center",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_center",
        description="Word horizontal center.",
    ),
    ("word", "right"): ExpressionPropertySpecification(
        object_name="word",
        name="right",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_right",
        description="Word right X position.",
    ),
    ("word", "width"): ExpressionPropertySpecification(
        object_name="word",
        name="width",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_width",
        description="Word width in pixels.",
    ),
    ("word", "top"): ExpressionPropertySpecification(
        object_name="word",
        name="top",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_top",
        description="Word top Y position.",
    ),
    ("word", "middle"): ExpressionPropertySpecification(
        object_name="word",
        name="middle",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_middle",
        description="Word vertical center.",
    ),
    ("word", "bottom"): ExpressionPropertySpecification(
        object_name="word",
        name="bottom",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_bottom",
        description="Word bottom Y position.",
    ),
    ("word", "height"): ExpressionPropertySpecification(
        object_name="word",
        name="height",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_height",
        description="Word height in pixels.",
    ),
    ("word", "x"): ExpressionPropertySpecification(
        object_name="word",
        name="x",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_x",
        description="Word anchor X position.",
    ),
    ("word", "y"): ExpressionPropertySpecification(
        object_name="word",
        name="y",
        type="int",
        available_scopes=WORD_SCOPES,
        source_variable="word_y",
        description="Word anchor Y position.",
    ),
    ("word", "text"): ExpressionPropertySpecification(
        object_name="word",
        name="text",
        type="str",
        available_scopes=WORD_SCOPES,
        source_variable=None,
        description="Visible word text.",
    ),
    ("word", "trimmed_text"): ExpressionPropertySpecification(
        object_name="word",
        name="trimmed_text",
        type="str",
        available_scopes=WORD_SCOPES,
        source_variable=None,
        description="Visible word text without outer spaces.",
    ),
    ("style", "primary_color"): ExpressionPropertySpecification(
        object_name="style",
        name="primary_color",
        type="str",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Current line style primary ASS color.",
    ),
    ("style", "name"): ExpressionPropertySpecification(
        object_name="style",
        name="name",
        type="str",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Current line style name.",
    ),
    ("style", "secondary_color"): ExpressionPropertySpecification(
        object_name="style",
        name="secondary_color",
        type="str",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Current line style secondary ASS color.",
    ),
    ("style", "outline_color"): ExpressionPropertySpecification(
        object_name="style",
        name="outline_color",
        type="str",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Current line style outline ASS color.",
    ),
    ("style", "shadow_color"): ExpressionPropertySpecification(
        object_name="style",
        name="shadow_color",
        type="str",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Current line style shadow ASS color.",
    ),
    ("style", "outline"): ExpressionPropertySpecification(
        object_name="style",
        name="outline",
        type="float",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Current line style outline width.",
    ),
    ("metadata", "res_x"): ExpressionPropertySpecification(
        object_name="metadata",
        name="res_x",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Script horizontal resolution in pixels.",
    ),
    ("metadata", "res_y"): ExpressionPropertySpecification(
        object_name="metadata",
        name="res_y",
        type="int",
        available_scopes=LINE_SCOPES,
        source_variable=None,
        description="Script vertical resolution in pixels.",
    ),
    ("syl", "start"): ExpressionPropertySpecification(
        object_name="syl",
        name="start",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_start",
        description="Syllable start time in ms.",
    ),
    ("syl", "end"): ExpressionPropertySpecification(
        object_name="syl",
        name="end",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_end",
        description="Syllable end time in ms.",
    ),
    ("syl", "dur"): ExpressionPropertySpecification(
        object_name="syl",
        name="dur",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_dur",
        description="Syllable duration in ms.",
    ),
    ("syl", "kdur"): ExpressionPropertySpecification(
        object_name="syl",
        name="kdur",
        type="float",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_kdur",
        description="Syllable duration in centiseconds.",
    ),
    ("syl", "mid"): ExpressionPropertySpecification(
        object_name="syl",
        name="mid",
        type="float",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_mid",
        description="Syllable temporal midpoint.",
    ),
    ("syl", "n"): ExpressionPropertySpecification(
        object_name="syl",
        name="n",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_n",
        description="Total number of syllables in the line.",
    ),
    ("syl", "i"): ExpressionPropertySpecification(
        object_name="syl",
        name="i",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_i",
        description="Syllable index in the line.",
    ),
    ("syl", "left"): ExpressionPropertySpecification(
        object_name="syl",
        name="left",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_left",
        description="Syllable left X position.",
    ),
    ("syl", "center"): ExpressionPropertySpecification(
        object_name="syl",
        name="center",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_center",
        description="Syllable horizontal center.",
    ),
    ("syl", "right"): ExpressionPropertySpecification(
        object_name="syl",
        name="right",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_right",
        description="Syllable right X position.",
    ),
    ("syl", "width"): ExpressionPropertySpecification(
        object_name="syl",
        name="width",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_width",
        description="Syllable width in pixels.",
    ),
    ("syl", "top"): ExpressionPropertySpecification(
        object_name="syl",
        name="top",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_top",
        description="Syllable top Y position.",
    ),
    ("syl", "middle"): ExpressionPropertySpecification(
        object_name="syl",
        name="middle",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_middle",
        description="Syllable vertical center.",
    ),
    ("syl", "bottom"): ExpressionPropertySpecification(
        object_name="syl",
        name="bottom",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_bottom",
        description="Syllable bottom Y position.",
    ),
    ("syl", "height"): ExpressionPropertySpecification(
        object_name="syl",
        name="height",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_height",
        description="Syllable height in pixels.",
    ),
    ("syl", "x"): ExpressionPropertySpecification(
        object_name="syl",
        name="x",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_x",
        description="Syllable anchor X position.",
    ),
    ("syl", "y"): ExpressionPropertySpecification(
        object_name="syl",
        name="y",
        type="int",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable="syl_y",
        description="Syllable anchor Y position.",
    ),
    ("syl", "tag"): ExpressionPropertySpecification(
        object_name="syl",
        name="tag",
        type="str",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable=None,
        description="Karaoke timing tag family, for example \\k or \\kf.",
    ),
    ("syl", "inline_fx"): ExpressionPropertySpecification(
        object_name="syl",
        name="inline_fx",
        type="str",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable=None,
        description="Inline fx marker parsed from karaoke overrides.",
    ),
    ("syl", "text"): ExpressionPropertySpecification(
        object_name="syl",
        name="text",
        type="str",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable=None,
        description="Visible syllable text without ASS tags.",
    ),
    ("syl", "trimmed_text"): ExpressionPropertySpecification(
        object_name="syl",
        name="trimmed_text",
        type="str",
        available_scopes=frozenset({Scope.SYL, Scope.CHAR}),
        source_variable=None,
        description="Visible syllable text without ASS tags or outer spaces.",
    ),
    ("char", "n"): ExpressionPropertySpecification(
        object_name="char",
        name="n",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_n",
        description="Total number of characters in the current line.",
    ),
    ("char", "i"): ExpressionPropertySpecification(
        object_name="char",
        name="i",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_i",
        description="Character index in the current line.",
    ),
    ("char", "left"): ExpressionPropertySpecification(
        object_name="char",
        name="left",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_left",
        description="Character left X position.",
    ),
    ("char", "center"): ExpressionPropertySpecification(
        object_name="char",
        name="center",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_center",
        description="Character horizontal center.",
    ),
    ("char", "right"): ExpressionPropertySpecification(
        object_name="char",
        name="right",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_right",
        description="Character right X position.",
    ),
    ("char", "width"): ExpressionPropertySpecification(
        object_name="char",
        name="width",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_width",
        description="Character width in pixels.",
    ),
    ("char", "top"): ExpressionPropertySpecification(
        object_name="char",
        name="top",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_top",
        description="Character top Y position.",
    ),
    ("char", "middle"): ExpressionPropertySpecification(
        object_name="char",
        name="middle",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_middle",
        description="Character vertical center.",
    ),
    ("char", "bottom"): ExpressionPropertySpecification(
        object_name="char",
        name="bottom",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_bottom",
        description="Character bottom Y position.",
    ),
    ("char", "height"): ExpressionPropertySpecification(
        object_name="char",
        name="height",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_height",
        description="Character height in pixels.",
    ),
    ("char", "x"): ExpressionPropertySpecification(
        object_name="char",
        name="x",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_x",
        description="Character anchor X position.",
    ),
    ("char", "y"): ExpressionPropertySpecification(
        object_name="char",
        name="y",
        type="int",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable="char_y",
        description="Character anchor Y position.",
    ),
    ("char", "text"): ExpressionPropertySpecification(
        object_name="char",
        name="text",
        type="str",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable=None,
        description="Visible character text.",
    ),
    ("char", "trimmed_text"): ExpressionPropertySpecification(
        object_name="char",
        name="trimmed_text",
        type="str",
        available_scopes=frozenset({Scope.CHAR}),
        source_variable=None,
        description="Visible character text without outer spaces.",
    ),
}
